export const countryList = [
  {
    name: "Afghanistan",
    iso2: "af",
    dialCode: "+93",
    format: "+93 12 345 6789",
    timeZones: ["Asia/Kabul"],
  },
  {
    name: "Albania",
    iso2: "al",
    dialCode: "+355",
    format: "+355 66 212 345",
    timeZones: ["Europe/Tirane"],
  },
  {
    name: "Algeria",
    iso2: "dz",
    dialCode: "+213",
    format: "+213 66 123 45 67",
    timeZones: ["Africa/Algiers"],
  },
  {
    name: "Andorra",
    iso2: "ad",
    dialCode: "+376",
    format: "+376 312 345",
    timeZones: ["Europe/Andorra"],
  },
  {
    name: "Angola",
    iso2: "ao",
    dialCode: "+244",
    format: "+244 923 123 456",
    timeZones: ["Africa/Luanda"],
  },
  {
    name: "Argentina",
    iso2: "ar",
    dialCode: "+54",
    format: "+54 9 11 2345 6789",
    timeZones: ["America/Argentina/Buenos_Aires"],
  },
  {
    name: "Armenia",
    iso2: "am",
    dialCode: "+374",
    format: "+374 77 123456",
    timeZones: ["Asia/Yerevan"],
  },
  {
    name: "Aruba",
    iso2: "aw",
    dialCode: "+297",
    format: "+297 560 1234",
    timeZones: ["America/Aruba"],
  },
  {
    name: "Australia",
    iso2: "au",
    dialCode: "+61",
    format: "+61 412 345 678",
    timeZones: [
      "Australia/Lord_Howe",
      "Antarctica/Macquarie",
      "Australia/Hobart",
      "Australia/Currie",
      "Australia/Melbourne",
      "Australia/Sydney",
      "Australia/Broken_Hill",
      "Australia/Brisbane",
      "Australia/Lindeman",
      "Australia/Adelaide",
      "Australia/Darwin",
      "Australia/Perth",
      "Australia/Eucla",
    ],
  },
  {
    name: "Austria",
    iso2: "at",
    dialCode: "+43",
    format: "+43 664 123456",
    timeZones: ["Europe/Vienna"],
  },
  {
    name: "Azerbaijan",
    iso2: "az",
    dialCode: "+994",
    format: "+994 40 123 45 67",
    timeZones: ["Asia/Baku"],
  },
  {
    name: "Bahrain",
    iso2: "bh",
    dialCode: "+973",
    format: "+973 3600 1234",
    timeZones: ["Asia/Bahrain"],
  },
  {
    name: "Bangladesh",
    iso2: "bd",
    dialCode: "+880",
    format: "+880 1812-345678",
    timeZones: ["Asia/Dhaka"],
  },
  {
    name: "Belarus",
    iso2: "by",
    dialCode: "+375",
    format: "+375 29 491-23-45",
    timeZones: ["Europe/Minsk"],
  },
  {
    name: "Belgium",
    iso2: "be",
    dialCode: "+32",
    format: "+32 471 12 34 56",
    timeZones: ["Europe/Brussels"],
  },
  {
    name: "Belize",
    iso2: "bz",
    dialCode: "+501",
    format: "+501 600 1234",
    timeZones: ["America/Belize"],
  },
  {
    name: "Benin",
    iso2: "bj",
    dialCode: "+229",
    format: "+229 90 12 3456",
    timeZones: ["Africa/Porto-Novo"],
  },
  {
    name: "Bhutan",
    iso2: "bt",
    dialCode: "+975",
    format: "+975 17 12 3456",
    timeZones: ["Asia/Thimphu"],
  },
  {
    name: "Bolivia",
    iso2: "bo",
    dialCode: "+591",
    format: "+591 71234567",
    timeZones: ["America/La_Paz"],
  },
  {
    name: "Bosnia and Herzegovina",
    iso2: "ba",
    dialCode: "+387",
    format: "+387 61 123 456",
    timeZones: ["Europe/Sarajevo"],
  },
  {
    name: "Botswana",
    iso2: "bw",
    dialCode: "+267",
    format: "+267 71 123 456",
    timeZones: ["Africa/Gaborone"],
  },
  {
    name: "Brazil",
    iso2: "br",
    dialCode: "+55",
    format: "+55 15 91234-5678",
    timeZones: [
      "America/Noronha",
      "America/Belem",
      "America/Fortaleza",
      "America/Recife",
      "America/Araguaina",
      "America/Maceio",
      "America/Bahia",
      "America/Sao_Paulo",
      "America/Campo_Grande",
      "America/Cuiaba",
      "America/Santarem",
      "America/Porto_Velho",
      "America/Boa_Vista",
      "America/Manaus",
      "America/Eirunepe",
      "America/Rio_Branco",
    ],
  },
  {
    name: "British Indian Ocean Territory",
    iso2: "io",
    dialCode: "+246",
    format: "+246 380 1234",
    timeZones: ["Indian/Chagos"],
  },
  {
    name: "Brunei",
    iso2: "bn",
    dialCode: "+673",
    format: "+673 712 3456",
    timeZones: ["Asia/Brunei"],
  },
  {
    name: "Bulgaria",
    iso2: "bg",
    dialCode: "+359",
    format: "+359 48 123 456",
    timeZones: ["Europe/Sofia"],
  },
  {
    name: "Burkina Faso",
    iso2: "bf",
    dialCode: "+226",
    format: "+226 70 12 345",
    timeZones: ["Africa/Ouagadougou"],
  },
  {
    name: "Burundi",
    iso2: "bi",
    dialCode: "+257",
    format: "+257 79 12 3456",
    timeZones: ["Africa/Bujumbura"],
  },
  {
    name: "Cambodia",
    iso2: "kh",
    dialCode: "+855",
    format: "+855 12 345 678",
    timeZones: ["Asia/Phnom_Penh"],
  },
  {
    name: "Cameroon",
    iso2: "cm",
    dialCode: "+237",
    format: "+237 6 12 34 5678",
    timeZones: ["Africa/Douala"],
  },
  {
    name: "Canada",
    iso2: "ca",
    dialCode: "+1",
    format: "+1 (204) 234 5678",
    timeZones: [
      "America/St_Johns",
      "America/Halifax",
      "America/Glace_Bay",
      "America/Moncton",
      "America/Goose_Bay",
      "America/Blanc-Sablon",
      "America/Toronto",
      "America/Nipigon",
      "America/Thunder_Bay",
      "America/Iqaluit",
      "America/Pangnirtung",
      "America/Atikokan",
      "America/Winnipeg",
      "America/Rainy_River",
      "America/Resolute",
      "America/Rankin_Inlet",
      "America/Regina",
      "America/Swift_Current",
      "America/Edmonton",
      "America/Cambridge_Bay",
      "America/Yellowknife",
      "America/Inuvik",
      "America/Creston",
      "America/Dawson_Creek",
      "America/Fort_Nelson",
      "America/Vancouver",
      "America/Whitehorse",
      "America/Dawson",
    ],
  },
  {
    name: "Cape Verde",
    iso2: "cv",
    dialCode: "+238",
    format: "+238 991 1234",
    timeZones: ["Atlantic/Cape_Verde"],
  },
  {
    name: "Caribbean Netherlands",
    iso2: "bq",
    dialCode: "+599",
    format: "+599 318 1234",
    timeZones: ["America/Curacao"],
  },
  {
    name: "Central African Republic",
    iso2: "cf",
    dialCode: "+236",
    format: "+236 70 01 2345",
    timeZones: ["Africa/Bangui"],
  },
  {
    name: "Chad",
    iso2: "td",
    dialCode: "+235",
    format: "+235 63 01 23 45",
    timeZones: ["Africa/Ndjamena"],
  },
  {
    name: "Chile",
    iso2: "cl",
    dialCode: "+56",
    format: "+56 9 6123 4567",
    timeZones: ["America/Santiago", "Pacific/Easter"],
  },
  {
    name: "China",
    iso2: "cn",
    dialCode: "+86",
    format: "+86 131 2345 6789",
    timeZones: ["Asia/Shanghai", "Asia/Urumqi"],
  },
  {
    name: "Christmas Island",
    iso2: "cx",
    dialCode: "+61",
    format: "+61 89164 1234",
    timeZones: ["Indian/Christmas"],
  },
  {
    name: "Cocos (Keeling) Islands",
    iso2: "cc",
    dialCode: "+61",
    format: "+61 89123 4567",
    timeZones: ["Indian/Cocos"],
  },
  {
    name: "Colombia",
    iso2: "co",
    dialCode: "+57",
    format: "+57 321 1234567",
    timeZones: ["America/Bogota"],
  },
  {
    name: "Comoros",
    iso2: "km",
    dialCode: "+269",
    format: "+269 321 2345",
    timeZones: ["Indian/Comoro"],
  },
  {
    name: "Congo (DRC)",
    iso2: "cd",
    dialCode: "+243",
    format: "+243 97 123 4567",
    timeZones: ["Africa/Kinshasa", "Africa/Lubumbashi"],
  },
  {
    name: "Congo (Republic)",
    iso2: "cg",
    dialCode: "+242",
    format: "+242 06 123 4567",
    timeZones: ["Africa/Brazzaville"],
  },
  {
    name: "Cook Islands",
    iso2: "ck",
    dialCode: "+682",
    format: "+682 71 234",
    timeZones: ["Pacific/Rarotonga"],
  },
  {
    name: "Costa Rica",
    iso2: "cr",
    dialCode: "+506",
    format: "+506 8312 3456",
    timeZones: ["America/Costa_Rica"],
  },
  {
    name: "Côte d’Ivoire",
    iso2: "ci",
    dialCode: "+225",
    format: "+225 01 23 45 67",
    timeZones: ["Africa/Abidjan"],
  },
  {
    name: "Croatia",
    iso2: "hr",
    dialCode: "+385",
    format: "+385 91 234 5678",
    timeZones: ["Europe/Zagreb"],
  },
  {
    name: "Cuba",
    iso2: "cu",
    dialCode: "+53",
    format: "+53 5 1234567",
    timeZones: ["America/Havana"],
  },
  {
    name: "Curaçao",
    iso2: "cw",
    dialCode: "+599",
    format: "+599 9 518 1234",
    timeZones: ["America/Curacao"],
  },
  {
    name: "Cyprus",
    iso2: "cy",
    dialCode: "+357",
    format: "+357 96 123456",
    timeZones: ["Asia/Nicosia"],
  },
  {
    name: "Czech Republic",
    iso2: "cz",
    dialCode: "+420",
    format: "+420 601 123 456",
    timeZones: ["Europe/Prague"],
  },
  {
    name: "Denmark",
    iso2: "dk",
    dialCode: "+45",
    format: "+45 20 12 34 56",
    timeZones: ["Europe/Copenhagen"],
  },
  {
    name: "Djibouti",
    iso2: "dj",
    dialCode: "+253",
    format: "+253 77 83 10 01",
    timeZones: ["Africa/Djibouti"],
  },
  {
    name: "Ecuador",
    iso2: "ec",
    dialCode: "+593",
    format: "+593 99 123 4567",
    timeZones: ["America/Guayaquil", "Pacific/Galapagos"],
  },
  {
    name: "Egypt",
    iso2: "eg",
    dialCode: "+20",
    format: "+20 10 1234 5678",
    timeZones: ["Africa/Cairo"],
  },
  {
    name: "El Salvador",
    iso2: "sv",
    dialCode: "+503",
    format: "+503 7012 3456",
    timeZones: ["America/El_Salvador"],
  },
  {
    name: "Equatorial Guinea",
    iso2: "gq",
    dialCode: "+240",
    format: "+240 222 123 456",
    timeZones: ["Africa/Malabo"],
  },
  {
    name: "Eritrea",
    iso2: "er",
    dialCode: "+291",
    format: "+291 7 123 456",
    timeZones: ["Africa/Asmara"],
  },
  {
    name: "Estonia",
    iso2: "ee",
    dialCode: "+372",
    format: "+372 5123 4567",
    timeZones: ["Europe/Tallinn"],
  },
  {
    name: "Eswatini",
    iso2: "sz",
    dialCode: "+268",
    format: "+268 7602 1234",
    timeZones: ["Africa/Mbabane"],
  },
  {
    name: "Ethiopia",
    iso2: "et",
    dialCode: "+251",
    format: "+251 91 123 4567",
    timeZones: ["Africa/Addis_Ababa"],
  },
  {
    name: "Falkland Islands",
    iso2: "fk",
    dialCode: "+500",
    format: "+500 51234",
    timeZones: ["Atlantic/Stanley"],
  },
  {
    name: "Faroe Islands",
    iso2: "fo",
    dialCode: "+298",
    format: "+298 234567",
    timeZones: ["Atlantic/Faroe"],
  },
  {
    name: "Fiji",
    iso2: "fj",
    dialCode: "+679",
    format: "+679 701 2345",
    timeZones: ["Pacific/Fiji"],
  },
  {
    name: "Finland",
    iso2: "fi",
    dialCode: "+358",
    format: "+358 50 1234567",
    timeZones: ["Europe/Helsinki"],
  },
  {
    name: "France",
    iso2: "fr",
    dialCode: "+33",
    format: "+33 6 12 34 56 78",
    timeZones: ["Europe/Paris"],
  },
  {
    name: "French Guiana",
    iso2: "gf",
    dialCode: "+594",
    format: "+594 694 20 12 34",
    timeZones: ["America/Cayenne"],
  },
  {
    name: "French Polynesia",
    iso2: "pf",
    dialCode: "+689",
    format: "+689 87 12 34 56",
    timeZones: ["Pacific/Tahiti"],
  },
  {
    name: "Gabon",
    iso2: "ga",
    dialCode: "+241",
    format: "+241 06 03 45 67",
    timeZones: ["Africa/Libreville"],
  },
  {
    name: "Gambia",
    iso2: "gm",
    dialCode: "+220",
    format: "+220 301 2345",
    timeZones: ["Africa/Banjul"],
  },
  {
    name: "Georgia",
    iso2: "ge",
    dialCode: "+995",
    format: "+995 595 123 456",
    timeZones: ["Asia/Tbilisi"],
  },
  {
    name: "Germany",
    iso2: "de",
    dialCode: "+49",
    format: "+49 151 12345678",
    timeZones: ["Europe/Berlin"],
  },
  {
    name: "Ghana",
    iso2: "gh",
    dialCode: "+233",
    format: "+233 23 123 4567",
    timeZones: ["Africa/Accra"],
  },
  {
    name: "Gibraltar",
    iso2: "gi",
    dialCode: "+350",
    format: "+350 56012345",
    timeZones: ["Europe/Gibraltar"],
  },
  {
    name: "Greece",
    iso2: "gr",
    dialCode: "+30",
    format: "+30 691 234 5678",
    timeZones: ["Europe/Athens"],
  },
  {
    name: "Greenland",
    iso2: "gl",
    dialCode: "+299",
    format: "+299 22 12 34",
    timeZones: ["America/Godthab"],
  },
  {
    name: "Guadeloupe",
    iso2: "gp",
    dialCode: "+590",
    format: "+590 690 30 12 34",
    timeZones: ["America/Guadeloupe"],
  },
  {
    name: "Guatemala",
    iso2: "gt",
    dialCode: "+502",
    format: "+502 4123 4567",
    timeZones: ["America/Guatemala"],
  },
  {
    name: "Guernsey",
    iso2: "gg",
    dialCode: "+44",
    format: "+44 7781 123456",
    timeZones: ["Europe/Guernsey"],
  },
  {
    name: "Guinea",
    iso2: "gn",
    dialCode: "+224",
    format: "+224 621 12 34 56",
    timeZones: ["Africa/Conakry"],
  },
  {
    name: "Guinea-Bissau",
    iso2: "gw",
    dialCode: "+245",
    format: "+245 955 1234",
    timeZones: ["Africa/Bissau"],
  },
  {
    name: "Guyana",
    iso2: "gy",
    dialCode: "+592",
    format: "+592 609 1234",
    timeZones: ["America/Guyana"],
  },
  {
    name: "Haiti",
    iso2: "ht",
    dialCode: "+509",
    format: "+509 34 12 3456",
    timeZones: ["America/Port-au-Prince"],
  },
  {
    name: "Honduras",
    iso2: "hn",
    dialCode: "+504",
    format: "+504 9123-4567",
    timeZones: ["America/Tegucigalpa"],
  },
  {
    name: "Hong Kong",
    iso2: "hk",
    dialCode: "+852",
    format: "+852 5123 4567",
    timeZones: ["Asia/Hong_Kong"],
  },
  {
    name: "Hungary",
    iso2: "hu",
    dialCode: "+36",
    format: "+36 20 123 4567",
    timeZones: ["Europe/Budapest"],
  },
  {
    name: "Iceland",
    iso2: "is",
    dialCode: "+354",
    format: "+354 611 2345",
    timeZones: ["Atlantic/Reykjavik"],
  },
  {
    name: "India",
    iso2: "in",
    dialCode: "+91",
    format: "+91 81234 56789",
    timeZones: ["Asia/Kolkata"],
  },
  {
    name: "Indonesia",
    iso2: "id",
    dialCode: "+62",
    format: "+62 812-3456-7890",
    timeZones: [
      "Asia/Jakarta",
      "Asia/Pontianak",
      "Asia/Makassar",
      "Asia/Jayapura",
    ],
  },
  {
    name: "Iran",
    iso2: "ir",
    dialCode: "+98",
    format: "+98 912 345 6789",
    timeZones: ["Asia/Tehran"],
  },
  {
    name: "Iraq",
    iso2: "iq",
    dialCode: "+964",
    format: "+964 791 123 4567",
    timeZones: ["Asia/Baghdad"],
  },
  {
    name: "Ireland",
    iso2: "ie",
    dialCode: "+353",
    format: "+353 85 123 4567",
    timeZones: ["Europe/Dublin"],
  },
  {
    name: "Israel",
    iso2: "il",
    dialCode: "+972",
    format: "+972 50-123-4567",
    timeZones: ["Asia/Jerusalem"],
  },
  {
    name: "Italy",
    iso2: "it",
    dialCode: "+39",
    format: "+39 345 123 4567",
    timeZones: ["Europe/Rome"],
  },
  {
    name: "Japan",
    iso2: "jp",
    dialCode: "+81",
    format: "+81 90-1234-5678",
    timeZones: ["Asia/Tokyo"],
  },
  {
    name: "Jersey",
    iso2: "je",
    dialCode: "+44",
    format: "+44 7700 123456",
    timeZones: ["Europe/Jersey"],
  },
  {
    name: "Jordan",
    iso2: "jo",
    dialCode: "+962",
    format: "+962 7 9012 3456",
    timeZones: ["Asia/Amman"],
  },
  {
    name: "Kazakhstan",
    iso2: "kz",
    dialCode: "+7",
    format: "+7 701 234 5678",
    timeZones: ["Asia/Almaty", "Asia/Qyzylorda", "Asia/Aqtobe", "Asia/Aqtau"],
  },
  {
    name: "Kenya",
    iso2: "ke",
    dialCode: "+254",
    format: "+254 712 123456",
    timeZones: ["Africa/Nairobi"],
  },
  {
    name: "Kiribati",
    iso2: "ki",
    dialCode: "+686",
    format: "+686 72012345",
    timeZones: ["Pacific/Tarawa"],
  },
  {
    name: "Kosovo",
    iso2: "xk",
    dialCode: "+383",
    format: "+383 44 123 456",
    timeZones: ["Europe/Belgrade"],
  },
  {
    name: "Kuwait",
    iso2: "kw",
    dialCode: "+965",
    format: "+965 500 12345",
    timeZones: ["Asia/Kuwait"],
  },
  {
    name: "Kyrgyzstan",
    iso2: "kg",
    dialCode: "+996",
    format: "+996 700 123 456",
    timeZones: ["Asia/Bishkek"],
  },
  {
    name: "Laos",
    iso2: "la",
    dialCode: "+856",
    format: "+856 20 91 234 567",
    timeZones: ["Asia/Vientiane"],
  },
  {
    name: "Latvia",
    iso2: "lv",
    dialCode: "+371",
    format: "+371 21 234 567",
    timeZones: ["Europe/Riga"],
  },
  {
    name: "Lebanon",
    iso2: "lb",
    dialCode: "+961",
    format: "+961 71 123 456",
    timeZones: ["Asia/Beirut"],
  },
  {
    name: "Lesotho",
    iso2: "ls",
    dialCode: "+266",
    format: "+266 6206 1234",
    timeZones: ["Africa/Maseru"],
  },
  {
    name: "Liberia",
    iso2: "lr",
    dialCode: "+231",
    format: "+231 77 012 3456",
    timeZones: ["Africa/Monrovia"],
  },
  {
    name: "Libya",
    iso2: "ly",
    dialCode: "+218",
    format: "+218 91 234 5678",
    timeZones: ["Africa/Tripoli"],
  },
  {
    name: "Liechtenstein",
    iso2: "li",
    dialCode: "+423",
    format: "+423 660 2345",
    timeZones: ["Europe/Vaduz"],
  },
  {
    name: "Lithuania",
    iso2: "lt",
    dialCode: "+370",
    format: "+370 612 34567",
    timeZones: ["Europe/Vilnius"],
  },
  {
    name: "Luxembourg",
    iso2: "lu",
    dialCode: "+352",
    format: "+352 621 123 456",
    timeZones: ["Europe/Luxembourg"],
  },
  {
    name: "Macau",
    iso2: "mo",
    dialCode: "+853",
    format: "+853 6612 3456",
    timeZones: ["Asia/Macau"],
  },
  {
    name: "Madagascar",
    iso2: "mg",
    dialCode: "+261",
    format: "+261 32 12 345 67",
    timeZones: ["Indian/Antananarivo"],
  },
  {
    name: "Malawi",
    iso2: "mw",
    dialCode: "+265",
    format: "+265 991 23 4567",
    timeZones: ["Africa/Blantyre"],
  },
  {
    name: "Malaysia",
    iso2: "my",
    dialCode: "+60",
    format: "+60 12-345 6789",
    timeZones: ["Asia/Kuala_Lumpur", "Asia/Kuching"],
  },
  {
    name: "Maldives",
    iso2: "mv",
    dialCode: "+960",
    format: "+960 771-2345",
    timeZones: ["Indian/Maldives"],
  },
  {
    name: "Mali",
    iso2: "ml",
    dialCode: "+223",
    format: "+223 65 01 23 45",
    timeZones: ["Africa/Bamako"],
  },
  {
    name: "Malta",
    iso2: "mt",
    dialCode: "+356",
    format: "+356 9696 1234",
    timeZones: ["Europe/Malta"],
  },
  {
    name: "Marshall Islands",
    iso2: "mh",
    dialCode: "+692",
    format: "+692 235 1234",
    timeZones: ["Pacific/Kwajalein", "Pacific/Majuro"],
  },
  {
    name: "Martinique",
    iso2: "mq",
    dialCode: "+596",
    format: "+596 696 20 12 34",
    timeZones: ["America/Martinique"],
  },
  {
    name: "Mauritania",
    iso2: "mr",
    dialCode: "+222",
    format: "+222 22 12 34 56",
    timeZones: ["Africa/Nouakchott"],
  },
  {
    name: "Mauritius",
    iso2: "mu",
    dialCode: "+230",
    format: "+230 5 123 4567",
    timeZones: ["Indian/Mauritius"],
  },
  {
    name: "Mayotte",
    iso2: "yt",
    dialCode: "+262",
    format: "+262 639 12 34 56",
    timeZones: ["Indian/Mayotte"],
  },
  {
    name: "Mexico",
    iso2: "mx",
    dialCode: "+52",
    format: "+52 1 33 1234 5678",
    timeZones: [
      "America/Tijuana",
      "America/Hermosillo",
      "America/Mazatlan",
      "America/Chihuahua",
      "America/Ojinaga",
      "America/Mexico_City",
      "America/Merida",
      "America/Monterrey",
      "America/Matamoros",
      "America/Bahia_Banderas",
      "America/Cancun",
    ],
  },
  {
    name: "Micronesia",
    iso2: "fm",
    dialCode: "+691",
    format: "+691 350 1234",
    timeZones: ["Pacific/Chuuk", "Pacific/Kosrae", "Pacific/Pohnpei"],
  },
  {
    name: "Moldova",
    iso2: "md",
    dialCode: "+373",
    format: "+373 600 12345",
    timeZones: ["Europe/Chisinau"],
  },
  {
    name: "Monaco",
    iso2: "mc",
    dialCode: "+377",
    format: "+377 6 12 34 56 78",
    timeZones: ["Europe/Monaco"],
  },
  {
    name: "Mongolia",
    iso2: "mn",
    dialCode: "+976",
    format: "+976 8812 3456",
    timeZones: ["Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"],
  },
  {
    name: "Montenegro",
    iso2: "me",
    dialCode: "+382",
    format: "+382 67 123 456",
    timeZones: ["Europe/Podgorica"],
  },
  {
    name: "Morocco",
    iso2: "ma",
    dialCode: "+212",
    format: "+212 650-123456",
    timeZones: ["Africa/Casablanca"],
  },
  {
    name: "Mozambique",
    iso2: "mz",
    dialCode: "+258",
    format: "+258 82 123 4567",
    timeZones: ["Africa/Maputo"],
  },
  {
    name: "Myanmar",
    iso2: "mm",
    dialCode: "+95",
    format: "+95 9 212 3456",
    timeZones: ["Asia/Yangon"],
  },
  {
    name: "Namibia",
    iso2: "na",
    dialCode: "+264",
    format: "+264 60 123 4567",
    timeZones: ["Africa/Windhoek"],
  },
  {
    name: "Nauru",
    iso2: "nr",
    dialCode: "+674",
    format: "+674 555 1234",
    timeZones: ["Pacific/Nauru"],
  },
  {
    name: "Nepal",
    iso2: "np",
    dialCode: "+977",
    format: "+977 984-1234567",
    timeZones: ["Asia/Kathmandu"],
  },
  {
    name: "Netherlands",
    iso2: "nl",
    dialCode: "+31",
    format: "+31 6 12345678",
    timeZones: ["Europe/Amsterdam"],
  },
  {
    name: "New Caledonia",
    iso2: "nc",
    dialCode: "+687",
    format: "+687 75.12.34",
    timeZones: ["Pacific/Noumea"],
  },
  {
    name: "New Zealand",
    iso2: "nz",
    dialCode: "+64",
    format: "+64 21 123 4567",
    timeZones: ["Pacific/Auckland", "Pacific/Chatham"],
  },
  {
    name: "Nicaragua",
    iso2: "ni",
    dialCode: "+505",
    format: "+505 8123 4567",
    timeZones: ["America/Managua"],
  },
  {
    name: "Niger",
    iso2: "ne",
    dialCode: "+227",
    format: "+227 93 12 34 56",
    timeZones: ["Africa/Niamey"],
  },
  {
    name: "Nigeria",
    iso2: "ng",
    dialCode: "+234",
    format: "+234 805 123 4567",
    timeZones: ["Africa/Lagos"],
  },
  {
    name: "Niue",
    iso2: "nu",
    dialCode: "+683",
    format: "+683 1234",
    timeZones: ["Pacific/Niue"],
  },
  {
    name: "Norfolk Island",
    iso2: "nf",
    dialCode: "+672",
    format: "+672 3 22123",
    timeZones: ["Pacific/Norfolk"],
  },
  {
    name: "North Korea",
    iso2: "kp",
    dialCode: "+850",
    format: "+850 192 1234",
    timeZones: ["Asia/Pyongyang"],
  },
  {
    name: "North Macedonia",
    iso2: "mk",
    dialCode: "+389",
    format: "+389 72 123 456",
    timeZones: ["Europe/Skopje"],
  },
  {
    name: "Norway",
    iso2: "no",
    dialCode: "+47",
    format: "+47 406 12 345",
    timeZones: ["Europe/Oslo"],
  },
  {
    name: "Oman",
    iso2: "om",
    dialCode: "+968",
    format: "+968 9212 3456",
    timeZones: ["Asia/Muscat"],
  },
  {
    name: "Pakistan",
    iso2: "pk",
    dialCode: "+92",
    format: "+92 301-2345678",
    timeZones: ["Asia/Karachi"],
  },
  {
    name: "Palau",
    iso2: "pw",
    dialCode: "+680",
    format: "+680 775 1234",
    timeZones: ["Pacific/Palau"],
  },
  {
    name: "Panama",
    iso2: "pa",
    dialCode: "+507",
    format: "+507 6123-4567",
    timeZones: ["America/Panama"],
  },
  {
    name: "Papua New Guinea",
    iso2: "pg",
    dialCode: "+675",
    format: "+675 7012 3456",
    timeZones: ["Pacific/Port_Moresby"],
  },
  {
    name: "Paraguay",
    iso2: "py",
    dialCode: "+595",
    format: "+595 961 456789",
    timeZones: ["America/Asuncion"],
  },
  {
    name: "Peru",
    iso2: "pe",
    dialCode: "+51",
    format: "+51 912 345 678",
    timeZones: ["America/Lima"],
  },
  {
    name: "Philippines",
    iso2: "ph",
    dialCode: "+63",
    format: "+63 918 123 4567",
    timeZones: ["Asia/Manila"],
  },
  {
    name: "Pitcairn Islands",
    iso2: "pn",
    dialCode: "+64",
    format: "+64 3 366 6778",
    timeZones: ["Pacific/Pitcairn"],
  },
  {
    name: "Poland",
    iso2: "pl",
    dialCode: "+48",
    format: "+48 512 345 678",
    timeZones: ["Europe/Warsaw"],
  },
  {
    name: "Portugal",
    iso2: "pt",
    dialCode: "+351",
    format: "+351 912 345 678",
    timeZones: ["Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"],
  },
  {
    name: "Qatar",
    iso2: "qa",
    dialCode: "+974",
    format: "+974 3312 3456",
    timeZones: ["Asia/Qatar"],
  },
  {
    name: "Réunion",
    iso2: "re",
    dialCode: "+262",
    format: "+262 692 12 34 56",
    timeZones: ["Indian/Reunion"],
  },
  {
    name: "Romania",
    iso2: "ro",
    dialCode: "+40",
    format: "+40 712 345 678",
    timeZones: ["Europe/Bucharest"],
  },
  {
    name: "Russia",
    iso2: "ru",
    dialCode: "+7",
    format: "+7 912 345-67-89",
    timeZones: [
      "Europe/Kaliningrad",
      "Europe/Moscow",
      "Europe/Simferopol",
      "Europe/Kirov",
      "Europe/Astrakhan",
      "Europe/Volgograd",
      "Europe/Saratov",
      "Europe/Ulyanovsk",
      "Europe/Samara",
      "Asia/Yekaterinburg",
      "Asia/Omsk",
      "Asia/Novosibirsk",
      "Asia/Barnaul",
      "Asia/Tomsk",
      "Asia/Novokuznetsk",
      "Asia/Krasnoyarsk",
      "Asia/Irkutsk",
      "Asia/Chita",
      "Asia/Yakutsk",
      "Asia/Khandyga",
      "Asia/Vladivostok",
      "Asia/Ust-Nera",
      "Asia/Magadan",
      "Asia/Sakhalin",
      "Asia/Srednekolymsk",
      "Asia/Kamchatka",
      "Asia/Anadyr",
    ],
  },
  {
    name: "Rwanda",
    iso2: "rw",
    dialCode: "+250",
    format: "+250 722 123 456",
    timeZones: ["Africa/Kigali"],
  },
  {
    name: "Saint Barthélemy",
    iso2: "bl",
    dialCode: "+590",
    format: "+590 690 30 12 34",
    timeZones: ["America/St_Barthelemy"],
  },
  {
    name: "Saint Helena",
    iso2: "sh",
    dialCode: "+290",
    format: "+290 2710",
    timeZones: ["Atlantic/St_Helena"],
  },
  {
    name: "Saint Martin",
    iso2: "mf",
    dialCode: "+590",
    format: "+590 690 30 12 34",
    timeZones: ["America/Marigot"],
  },
  {
    name: "Saint Pierre and Miquelon",
    iso2: "pm",
    dialCode: "+508",
    format: "+508 551 12 34",
    timeZones: ["America/Miquelon"],
  },
  {
    name: "Samoa",
    iso2: "ws",
    dialCode: "+685",
    format: "+685 721 2345",
    timeZones: ["Pacific/Apia"],
  },
  {
    name: "San Marino",
    iso2: "sm",
    dialCode: "+378",
    format: "+378 66 66 12 34",
    timeZones: ["Europe/San_Marino"],
  },
  {
    name: "São Tomé and Príncipe",
    iso2: "st",
    dialCode: "+239",
    format: "+239 981 2345",
    timeZones: ["Africa/Sao_Tome"],
  },
  {
    name: "Saudi Arabia",
    iso2: "sa",
    dialCode: "+966",
    format: "+966 54 123 4567",
    timeZones: ["Asia/Riyadh"],
  },
  {
    name: "Senegal",
    iso2: "sn",
    dialCode: "+221",
    format: "+221 70 123 45 67",
    timeZones: ["Africa/Dakar"],
  },
  {
    name: "Serbia",
    iso2: "rs",
    dialCode: "+381",
    format: "+381 60 1234567",
    timeZones: ["Europe/Belgrade"],
  },
  {
    name: "Seychelles",
    iso2: "sc",
    dialCode: "+248",
    format: "+248 2 510 123",
    timeZones: ["Indian/Mahe"],
  },
  {
    name: "Sierra Leone",
    iso2: "sl",
    dialCode: "+232",
    format: "+232 25 123456",
    timeZones: ["Africa/Freetown"],
  },
  {
    name: "Singapore",
    iso2: "sg",
    dialCode: "+65",
    format: "+65 8123 4567",
    timeZones: ["Asia/Singapore"],
  },
  {
    name: "Slovakia",
    iso2: "sk",
    dialCode: "+421",
    format: "+421 912 123 456",
    timeZones: ["Europe/Bratislava"],
  },
  {
    name: "Slovenia",
    iso2: "si",
    dialCode: "+386",
    format: "+386 31 123 456",
    timeZones: ["Europe/Ljubljana"],
  },
  {
    name: "Solomon Islands",
    iso2: "sb",
    dialCode: "+677",
    format: "+677 74 21234",
    timeZones: ["Pacific/Guadalcanal"],
  },
  {
    name: "Somalia",
    iso2: "so",
    dialCode: "+252",
    format: "+252 61 234 5678",
    timeZones: ["Africa/Mogadishu"],
  },
  {
    name: "South Africa",
    iso2: "za",
    dialCode: "+27",
    format: "+27 71 123 4567",
    timeZones: ["Africa/Johannesburg"],
  },
  {
    name: "South Korea",
    iso2: "kr",
    dialCode: "+82",
    format: "+82 10-1234-5678",
    timeZones: ["Asia/Seoul"],
  },
  {
    name: "South Sudan",
    iso2: "ss",
    dialCode: "+211",
    format: "+211 97 123 4567",
    timeZones: ["Africa/Juba"],
  },
  {
    name: "Spain",
    iso2: "es",
    dialCode: "+34",
    format: "+34 612 34 56 78",
    timeZones: ["Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"],
  },
  {
    name: "Sri Lanka",
    iso2: "lk",
    dialCode: "+94",
    format: "+94 71 234 5678",
    timeZones: ["Asia/Colombo"],
  },
  {
    name: "Sudan",
    iso2: "sd",
    dialCode: "+249",
    format: "+249 91 123 1234",
    timeZones: ["Africa/Khartoum"],
  },
  {
    name: "Suriname",
    iso2: "sr",
    dialCode: "+597",
    format: "+597 741-2345",
    timeZones: ["America/Paramaribo"],
  },
  {
    name: "Svalbard and Jan Mayen",
    iso2: "sj",
    dialCode: "+47",
    format: "+47 79 02 12 34",
    timeZones: ["Arctic/Longyearbyen"],
  },
  {
    name: "Sweden",
    iso2: "se",
    dialCode: "+46",
    format: "+46 73 123 45 67",
    timeZones: ["Europe/Stockholm"],
  },
  {
    name: "Switzerland",
    iso2: "ch",
    dialCode: "+41",
    format: "+41 78 123 45 67",
    timeZones: ["Europe/Zurich"],
  },
  {
    name: "Syria",
    iso2: "sy",
    dialCode: "+963",
    format: "+963 944 567 890",
    timeZones: ["Asia/Damascus"],
  },
  {
    name: "Taiwan",
    iso2: "tw",
    dialCode: "+886",
    format: "+886 912 345 678",
    timeZones: ["Asia/Taipei"],
  },
  {
    name: "Tajikistan",
    iso2: "tj",
    dialCode: "+992",
    format: "+992 93 123 45 67",
    timeZones: ["Asia/Dushanbe"],
  },
  {
    name: "Tanzania",
    iso2: "tz",
    dialCode: "+255",
    format: "+255 62 123 4567",
    timeZones: ["Africa/Dar_es_Salaam"],
  },
  {
    name: "Thailand",
    iso2: "th",
    dialCode: "+66",
    format: "+66 8 1234 5678",
    timeZones: ["Asia/Bangkok"],
  },
  {
    name: "Timor-Leste",
    iso2: "tl",
    dialCode: "+670",
    format: "+670 7721 2345",
    timeZones: ["Asia/Dili"],
  },
  {
    name: "Togo",
    iso2: "tg",
    dialCode: "+228",
    format: "+228 90 123 456",
    timeZones: ["Africa/Lome"],
  },
  {
    name: "Tokelau",
    iso2: "tk",
    dialCode: "+690",
    format: "+690 7290",
    timeZones: ["Pacific/Fakaofo"],
  },
  {
    name: "Tonga",
    iso2: "to",
    dialCode: "+676",
    format: "+676 771 5123",
    timeZones: ["Pacific/Tongatapu"],
  },
  {
    name: "Tunisia",
    iso2: "tn",
    dialCode: "+216",
    format: "+216 23 123 456",
    timeZones: ["Africa/Tunis"],
  },
  {
    name: "Turkey",
    iso2: "tr",
    dialCode: "+90",
    format: "+90 555 123 4567",
    timeZones: ["Europe/Istanbul"],
  },
  {
    name: "Turkmenistan",
    iso2: "tm",
    dialCode: "+993",
    format: "+993 66 123456",
    timeZones: ["Asia/Ashgabat"],
  },
  {
    name: "Tuvalu",
    iso2: "tv",
    dialCode: "+688",
    format: "+688 9012",
    timeZones: ["Pacific/Funafuti"],
  },
  {
    name: "Uganda",
    iso2: "ug",
    dialCode: "+256",
    format: "+256 71 2345678",
    timeZones: ["Africa/Kampala"],
  },
  {
    name: "Ukraine",
    iso2: "ua",
    dialCode: "+380",
    format: "+380 39 123 4567",
    timeZones: ["Europe/Kiev", "Europe/Uzhgorod", "Europe/Zaporozhye"],
  },
  {
    name: "United Arab Emirates",
    iso2: "ae",
    dialCode: "+971",
    format: "+971 50 123 4567",
    timeZones: ["Asia/Dubai"],
  },
  {
    name: "United Kingdom",
    iso2: "gb",
    dialCode: "+44",
    format: "+44 7700 900123",
    timeZones: ["Europe/London"],
  },
  {
    name: "United States",
    iso2: "us",
    dialCode: "+1",
    format: "+1 201-555-0123",
    timeZones: [
      "America/New_York",
      "America/Detroit",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/Indiana/Indianapolis",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Vevay",
      "America/Chicago",
      "America/Indiana/Tell_City",
      "America/Indiana/Knox",
      "America/Menominee",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "America/North_Dakota/Beulah",
      "America/Denver",
      "America/Boise",
      "America/Phoenix",
      "America/Los_Angeles",
      "America/Anchorage",
      "America/Juneau",
      "America/Sitka",
      "America/Metlakatla",
      "America/Yakutat",
      "America/Nome",
      "America/Adak",
      "Pacific/Honolulu",
    ],
  },
  {
    name: "Uruguay",
    iso2: "uy",
    dialCode: "+598",
    format: "+598 94 231 234",
    timeZones: ["America/Montevideo"],
  },
  {
    name: "Uzbekistan",
    iso2: "uz",
    dialCode: "+998",
    format: "+998 90 123 45 67",
    timeZones: ["Asia/Samarkand", "Asia/Tashkent"],
  },
  {
    name: "Vanuatu",
    iso2: "vu",
    dialCode: "+678",
    format: "+678 771 2345",
    timeZones: ["Pacific/Efate"],
  },
  {
    name: "Vatican City",
    iso2: "va",
    dialCode: "+379",
    format: "+379 366 1234567",
    timeZones: ["Europe/Vatican"],
  },
  {
    name: "Venezuela",
    iso2: "ve",
    dialCode: "+58",
    format: "+58 412-1234567",
    timeZones: ["America/Caracas"],
  },
  {
    name: "Vietnam",
    iso2: "vn",
    dialCode: "+84",
    format: "+84 91 123 45 67",
    timeZones: ["Asia/Ho_Chi_Minh"],
  },
  {
    name: "Wallis and Futuna",
    iso2: "wf",
    dialCode: "+681",
    format: "+681 50.12.34",
    timeZones: ["Pacific/Wallis"],
  },
  {
    name: "Yemen",
    iso2: "ye",
    dialCode: "+967",
    format: "+967 711 234 567",
    timeZones: ["Asia/Aden"],
  },
  {
    name: "Zambia",
    iso2: "zm",
    dialCode: "+260",
    format: "+260 95 5123456",
    timeZones: ["Africa/Lusaka"],
  },
  {
    name: "Zimbabwe",
    iso2: "zw",
    dialCode: "+263",
    format: "+263 71 123 4567",
    timeZones: ["Africa/Harare"],
  },
];
